### ISSUE TITLE
[BUG] Date format for UK or rest of the world

### ISSUE THREAD

**Issue by AMSAMSAMSAMS** [bixbydevelopers/bhs-tutorial-samples#1]
The time format for UK region (or any regions that uses 24 hours time format) is correct already when asked, it's in 24 hours following the phone settings.
However the DATE FORMAT is ALWAYS in US format which is **MMMM DD, YYY**.

Look at the screenshot!

![image](https://i.imgur.com/v12pzec.png)
![image](https://i.imgur.com/AQTD8vO.png)

It SHOULD follow the phone's settings! 
For UK region (or any regions that uses those formatting) it should be: **Wednesday, 8 March 2023** instead of **Wednesday, March 8, 2023**.

**Comment by AMSAMSAMSAMS** [comment]
I reported this so many times via Bixby bug report & also Samsung Members bug report but seems the only answers I get is just from BOT!!!
Shame on you Samsung!

**Comment by Crescendo-BLYAT** [comment]
Same, I reported the issue since a year ago but nobody's taking it seriously.

**Comment by AMSAMSAMSAMS** [comment]
@rogerkibbe @jpalioto Please rectify, thanks.

**Comment by rogerkibbe** [comment]
Please go to bixbydevelopers.com and click on support to report the bug here. That will get it to the right team.

Github issues should be relevant to the code in the repo

**Comment by AMSAMSAMSAMS** [comment]
Done & all I get is just BOT answering to my report.
Also I'm not developers, unless Bixby is intended only for developer use then Samsung should take on report SERIOUSLY.
I'm just user here & reporting bug I found.

**Comment by AMSAMSAMSAMS** [comment]
@rogerkibbe Also it's still NOT FIXED in the last update, so?

**Comment by Crescendo-BLYAT** [comment]
No fix... FUCK BIXBY TEAM!!

**Comment by AMSAMSAMSAMS** [comment]
https://github.com/bixbydevelopers/bhs-tutorial-samples/issues/1

**Comment by AMSAMSAMSAMS** [comment]
https://support.bixbydevelopers.com/hc/en-us/requests/6041
