### ISSUE TITLE
[BUG] Date format for UK or rest of the world STILL NOT FIXED IN LAST UPDATE

### ISSUE THREAD

**Issue by AMSAMSAMSAMS** [bixbydevelopers/bhs-tutorial-samples#2]
The time format for UK region (or any regions that uses 24 hours time format) is correct already when asked, it's in 24 hours following the phone settings.
However the DATE FORMAT is ALWAYS in US format which is **MMMM DD, YYY**.

Look at the screenshot!

![image](https://i.imgur.com/v12pzec.png)
![image](https://i.imgur.com/AQTD8vO.png)

It SHOULD follow the phone's settings! 
For UK region (or any regions that uses those formatting) it should be: **Wednesday, 8 March 2023** instead of **Wednesday, March 8, 2023**.

Done & all I get is just BOT answering to my report.
Also I'm not developers, unless Bixby is intended only for developer use then Samsung should take on report SERIOUSLY.
I'm just NORMAL USER here & reporting bug I found & devs never take my report seriously.

Also it's still NOT FIXED in the last update, so?

**Comment by AMSAMSAMSAMS** [comment]
@rogerkibbe @jpalioto So? Anyone can help report this to the DEAF BIXBY TEAM??

**Comment by AMSAMSAMSAMS** [comment]
@rogerkibbe @jpalioto And I will keep opening bug report till this bug passed to the relevant team. I expect a PROPER update.

**Comment by jpalioto** [comment]
This is not related to this repo. @rogerkibbe told you how to report general Bixby issues. That's your best course of action. All issues that are reported through

https://support.bixbydevelopers.com/hc/en-us/community/topics/360000183273-Feature-Requests

Get routed to the appropriate team and triaged by that team.
